# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [4]:
import numpy as np

### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [9]:
import matplotlib as plt
import networkx
import pandas as pd
!pip install geopandas

  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
   ---------------------------------------- 0.0/343.3 kB ? eta -:--:--
   ---- ----------------------------------- 41.0/343.3 kB 1.9 MB/s eta 0:00:01
   ------------- -------------------------- 112.6/343.3 kB 1.3 MB/s eta 0:00:01
   -------------------- ------------------- 174.1/343.3 kB 1.3 MB/s eta 0:00:01
   --------------------------- ------------ 235.5/343.3 kB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 286.7/343.3 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------  337.9/343.3 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 343.3/343.3 kB 1.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 660.6 kB/s eta 0:00:15
   ---------------------------------------- 0.1/9.9 MB 812.7 kB/s eta 0:00:1


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [7]:
a = np.array([2, 4, 6, 8])
print(a + 3)
print(2 * a)
print(a**2)
print(a-1)

[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [21]:

def g(h, f, x):
    return (f(x + h) - f(x)) / h

g_vec = np.vectorize(g)

x = 0

h = np.array([1e-1, 1e-2, 1e-3, 1e-4])

approx = g_vec(h, np.sin, x)

exact = np.cos(x)

print("x =", x)
print("Exact derivative:", exact)
print("Approximations:", approx)

for i, j in zip(h, approx):
    print(f"h = {i} -> Approximation = {j}, Error = {abs(j-exact)}")

x = 0
Exact derivative: 1.0
Approximations: [0.99833417 0.99998333 0.99999983 1.        ]
h = 0.1 -> Approximation = 0.9983341664682815, Error = 0.0016658335317184525
h = 0.01 -> Approximation = 0.9999833334166665, Error = 1.6666583333546647e-05
h = 0.001 -> Approximation = 0.9999998333333416, Error = 1.666666583632903e-07
h = 0.0001 -> Approximation = 0.9999999983333334, Error = 1.66666658252268e-09


###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [26]:
a= np.array([[2,1],[3,4]])
b= np.array([[5,2],[1,6]])
print(a @ b)
print(np.matmul(a,b))

[[11 10]
 [19 30]]
[[11 10]
 [19 30]]
