# Week 5 Day 2 Lab
### Problem 1
Create a neural network with:
- 2 input features
- 8 hidden neurons
- ReLU activation
- 1 sigmoid output neuron


In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(8, activation='relu', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape          ┃      Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ dense_2 (Dense)               │ (None, 8)             │           24 │
├───────────────────────────────┼───────────────────────┼──────────────┤
│ dense_3 (Dense)               │ (None, 1)             │            9 │
└───────────────────────────────┴───────────────────────┴──────────────┘

 Total params: 33 (132.00 B)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 0 (0.00 B)

### Problem 2
Create your own dataset and train the model for:

- 50 epochs
- 100 epochs
- 300 epochs

Compare the results.


In [3]:
import numpy as np

X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=float)

y = np.array([
    [0],
    [0],
    [0],
    [1]
], dtype=float)

def create_model():
    model = Sequential([
        Dense(8, activation='relu', input_shape=(2,)),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

for epochs in [50, 100, 300]:
    print(f"\nTraining for {epochs} epochs")

    model = create_model()
    model.fit(X, y, epochs=epochs, verbose=0)

    loss, accuracy = model.evaluate(X, y, verbose=0)
    predictions = (model.predict(X, verbose=0) > 0.5).astype(int)

    print(f"Loss: {loss:.4f}")
    print(f"Accuracy: {accuracy:.4f}")
    print("Predictions:")
    print(predictions.flatten())


Training for 50 epochs
Loss: 0.6908
Accuracy: 0.7500
Predictions:
[0 0 0 0]

Training for 100 epochs
Loss: 0.6439
Accuracy: 0.7500
Predictions:
[0 0 0 0]

Training for 300 epochs
Loss: 0.4824
Accuracy: 1.0000
Predictions:
[0 0 0 1]


### Problem 3

Replace the optimizer:

```python
optimizer="sgd"
```

Compare it with:

```python
optimizer="adam"
```


In [4]:
def create_model(optimizer):
    model = Sequential([
        Dense(8, activation='relu', input_shape=(2,)),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

for optimizer in ["sgd", "adam"]:
    print(f"\nOptimizer: {optimizer}")

    model = create_model(optimizer)
    model.fit(X, y, epochs=100, verbose=0)

    loss, accuracy = model.evaluate(X, y, verbose=0)

    print("Loss", loss)
    print("Accuracy", accuracy)


Optimizer: sgd
Loss 0.5831185579299927
Accuracy 0.75

Optimizer: adam
Loss 0.5904742479324341
Accuracy 1.0


### Problem 4
Create a neural network for the Iris dataset using:

- Input layer
- One hidden layer
- Three output neurons
- Softmax activation

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("iris.csv")

X = df.iloc[:, :-1].values

y = df.iloc[:, -1].values

encoder = LabelEncoder()
y = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=100, verbose=1)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

print("\nTest Accuracy:", accuracy)
print("Test Loss", loss)

Epoch 1/100


C:\Users\CharlesLiu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.3250 - loss: 2.7001
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.3250 - loss: 2.6057 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.3250 - loss: 2.5172
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3250 - loss: 2.4294
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.3250 - loss: 2.3404
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3250 - loss: 2.2613 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3250 - loss: 2.1750 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3250 - loss: 2.0924
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3250 - loss: 2.0106
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3250 - loss: 1.9368
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3250 - loss: 1.8516
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3250 - loss: 1.780